name: Maven CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven
      
    - name: Build database image
      run: docker build database --tag database
    
    - name: Start database service
      run: docker run -d -p 3306:3306 database:latest
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Copy compiled .jar to staging
      run: mkdir staging && cp target/*.jar staging
    
    - uses: actions/upload-artifact@v3
      with:
        name: Server JAR
        path: staging
